version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l debug
    depends_on:
      - grpc-backend
    networks:
      - grpc-network

  grpc-backend:
    build: ./backend
    ports:
      - "9090:9090"
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge
